# basic options
title:  coQuerel
author:  Hector Sainvet
email:  sainvet.hector@gmail.com
description:  Cultural Criss-Cross
github_username:  HectorSainvet

# Build settings
markdown:  kramdown
theme:  minima:
          date_format: "%b %-d, %Y"
          skin: sunrise
header_pages:
  - about.md
  - portfolio.md
