# basic options
title:  coQuerel
author:  Hector Sainvet
description:  Thoughts 
github_username:  HectorSainvet
keywords: coquerel

defaults :
  - scope:
      path: ""
    values:
        layout: default

minima :
date_format: "%b %-d, %Y"
skin: sunrise
header_pages:
  - about.md
  - languages.md

# Build settings
markdown:  kramdown
theme:  jekyll-theme-minimal

