# basic options
title:  coQuerel
author:  Hector Sainvet
description:  Cultural Criss-Cross
github_username:  HectorSainvet

minima :
date_format: "%b %-d, %Y"
skin: sunrise
header_pages:
  - about.md
  - languages.md

# Build settings
markdown:  kramdown
theme:  minima

